default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dance_development
  username: alexey
  password: 54ihanan

test:
  <<: *default
  database: dance_test
  username: alexey
  password: 54ihanan

production:
  <<: *default
  database: falcon
  username: deploy
  password: nastyafalcon
